# Site settings
title: Paradox Programming
header-img: img/home-bg.jpg
email: aki.legaspi@gmail.com
description: "Live to develop not Develop to live"
baseurl: "https://akilegaspi.github.io"
url: "https://akilegaspi.github.io"
twitter_username: akilegaspi 
github_username:  akilegaspi
facebook_username:  aki.legaspi

# Build settings
markdown: kramdown
highlighter: pygments
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
